config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "/dashboard" => "home#dashboard" , as: :dashboard

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

  resources :champions



end

app/models/champion.rb
class Champion < ApplicationRecord
  has_and_belongs_to_many :tags




  def self._get_list_page(params)

    _where = ' '
    _page = (params[:page].present?) ? params[:page] : 1

    if params[:search].present? && params[:search] != ''
      if !params[:search].blank?
        search_params = params[:search].gsub /'/, ''
        _where += " champions.name ILIKE '%#{search_params}%' "
      end
    end


    _items = Champion
                 .where(_where)
                 .order('champions.name ASC')
                 .paginate(:page => _page, :per_page => 10)

    return _items
  end

  def self._get_list_page_stats(params)
    _where = ' '
    _page = (params[:page].present?) ? params[:page] : 1

    if params[:search].present? && params[:search] != ''
      if !params[:search].blank?
        search_params = params[:search].gsub /'/, ''
        _where += " champions.name ILIKE '%#{search_params}%' "
      end
    end

    _count = Champion.where(_where).count
    _offset = (10 * _page.to_i) - 10

    return { info: {
        :amount => _count,
        :page => _page,
        :total_pages => (_count/10.to_f).ceil,
        :per_page => 10,
        :str => "Viewing #{_offset+1} to #{_offset+10} out of #{_count} champions",
    }}

  end

end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]
  #skip_before_action :verify_authenticity_token, only: [ :update, :create, :destroy]
  protect_from_forgery :except => [:create,:update,:destroy]
  
  # GET /champions
  # GET /champions.json
  def index
    @champions =  Champion._get_list_page(params)

    respond_to do |format|
        format.html { }
        format.json {

          if params[:detail] == 'true'
            _result = []
            @champions.each do |champ|
              _tmp = champ.attributes
              _tmp['tags'] = champ.tags.select('id,name')
              _result.push(_tmp)
            end
            render json: {:info => Champion._get_list_page_stats(params), :data =>_result }
          else
            render json: {:info => Champion._get_list_page_stats(params), :data =>@champions }
          end

        }

    end
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
    @tags = Tag.all
    @selected_tags = []
  end

  # GET /champions/1/edit
  def edit
    @tags = Tag.all
    @selected_tags = @champion.tags.pluck(:id)
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        _tmp_tags = (params['tags'].present?) ? params['tags'] : params['champion']['tags']
        _tags = Tag.where(:name => _tmp_tags).all
        @champion.tags << _tags
        format.html { redirect_to champions_path, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update

    respond_to do |format|
      if @champion.update(champion_params)

        if params['champion']['tags'].present? || params['tags'].present?
          _tmp_tags = (params['tags'].present?) ? params['tags'] : params['champion']['tags']
          @champion.tags.delete_all
          _tags = Tag.where(:name => _tmp_tags).all
          @champion.tags << _tags
        end

        format.html { redirect_to champions_path, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy

    if @champion
      @champion.destroy
    end
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_champion
    @champion = Champion.find(params[:id]) rescue false
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def champion_params
    params.require(:champion).permit(:name, :description)
  end

end

app/views/champions/_form.html.erb
<%= form_for(champion) do |f| %>
  <% if champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% champion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </fieldset>


  <fieldset class="form-group">
    <% @tags.each do |t| %>
      <%= f.label t.name  %>

      <% @selected = (@selected_tags.include?(t.id)) ? true : false %>
      <%= f.check_box :tags, {multiple: true, checked: @selected}, t.name,false %>

    <% end %>

  </fieldset>


  <fieldset class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Delete', @champion, method: :delete, data: { confirm: 'Are you sure?' } %>
| <%= link_to 'Cancel', champions_path %>

app/views/champions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Created at</th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= link_to champion.name, edit_champion_path(champion) %></td>
        <td>
          <% champion.tags.each do |_tag| %>
            <%= _tag.name %>
          <% end %>
        </td>
        <td><%= champion.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  <tr><td colspan="100%">
    <%= will_paginate @champions, {:link_separator => ' | '} %>
  </td> </tr>
</table>

<br>

<%= link_to 'New Champion', new_champion_path, class: "btn btn-primary" %>

app/views/champions/new.html.erb
<h1>New Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Cancel', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tags:</strong>
  <%= @champion.tags %>
</p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @champion.description %>
</p>

<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', champions_path %>